title: "Rajesh Balaji's Blog"
email: vasubalajimca@gmail.com
description: "My personal blog."
url: ""
baseurl: ""
navigation: "main"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

include:
  - _pages

author:
  name: "Rajesh Balaji"
  bio: "Software Engineer | Cloud Enthusiast"
  avatar: "/assets/images/profile.jpg"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:vasubalajimca@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rajesh-balaji-74787932/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rajeshbalaji"