title: "Rajesh Balaji's Blog"
email: vasubalajimca@gmail.com
description: "My personal blog."
url: ""
baseurl: ""

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

include:
  - _pages

author:
  name: "Rajesh Balaji"
  bio: "Welcome to my blog."